version: '3'
services:
  whyis-ubuntu:
    build:
      context: ../../../..
      dockerfile: docker/image/whyis-ubuntu/Dockerfile
    image: tetherlessworld/whyis-ubuntu:${WHYIS_IMAGE_TAG:-latest}
  whyis-server-deps:
    build:
      context: ../../../..
      dockerfile: docker/image/whyis-server-deps/Dockerfile
    image: tetherlessworld/whyis-server-deps:${WHYIS_IMAGE_TAG:-latest}
  whyis-server:
    container_name: "whyis-server"
    build:
      context: ../../../..
      dockerfile: docker/image/whyis-server/Dockerfile
    image: tetherlessworld/whyis-server:${WHYIS_IMAGE_TAG:-latest}
    ports:
      - "80:80"
      - "5000:5000"
    external_links:
      - blazegraph
      - redis
    entrypoint: /docker-entrypoint.sh
    command: tail -f /dev/null
