version: '3'
services:
  whyis-demo:
    container_name: "whyis-demo"
    image: ${WHYIS_DEMO_IMAGE:-tetherlessworld/whyis-demo:latest}
  whyis-integration:
    container_name: "whyis-integration"
    build:
      context: ../../..
      dockerfile: docker/image/whyis-integration/Dockerfile
    depends_on:
      - whyis-demo
    links:
      - whyis-demo:whyis
    image: tetherlessworld/whyis-integration:latest
    command: /docker-entrypoint.sh
