# Simple docker-compose file for local development:
# * Creates a redis server for celery and opens its port to localhost
# * Uses the whyis image for its pre-configured blazegraph.
#
# A production compose file would have a separate blazegraph container, and others.
version: '3'
services:
  whyis:
    container_name: "whyis"
    build:
      context: ../../..
      dockerfile: docker/image/whyis/Dockerfile
    depends_on:
      - whyis-deps
    image: tetherlessworld/whyis:${WHYIS_IMAGE_TAG:-latest}
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:6379:6379"
      - "127.0.0.1:8080:8080"
    command: tail -f /dev/null
  whyis-deps:
    container_name: "whyis-deps"
    build:
      context: ../../..
      dockerfile: docker/image/whyis-deps/Dockerfile
    image: tetherlessworld/whyis-deps:${WHYIS_IMAGE_TAG:-latest}
    command: tail -f /dev/null
