# whyis testing
# Adapted from https://circleci.com/blog/how-to-build-a-docker-image-on-circleci-2-0/
version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:18.06.0-ce
        environment:
          BUILD_MODE: master
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install bash
          command: apk update && apk add bash
      - run:
          name: Build application Docker image
          command: |
            cd docker/compose/dev && docker-compose build whyis
      - run:
          name: Run tests
          command: |
            bash .circleci/test-ci.sh
      - store_test_results:
          path: test-results
  