# whyis testing
# Adapted from https://circleci.com/blog/how-to-build-a-docker-image-on-circleci-2-0/
version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:18.06.0-ce
        environment:
          BUILD_MODE: master
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install system dependencies with apk
          command: apk update && apk add bash curl git
      - run:
          name: Install Docker Compose
          command: |
            curl -s -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Build application Docker image
          command: |
            cd docker/compose/dev && docker-compose build whyis
      - run:
          name: Run tests
          command: |
            bash .circleci/test-ci.sh
      - store_test_results:
          path: test-results
      - run:
          name: Push Docker image
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS && cd docker/compose/dev && docker-compose push whyis
