# whyis testing
# Adapted from https://circleci.com/blog/how-to-build-a-docker-image-on-circleci-2-0/
version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker/compose:1.24.1
    steps:
      - run:
          name: Install system dependencies with apk
          command: apk update && apk add bash git
      - checkout
      - setup_remote_docker
      - run:
          name: Build monolithic Docker image
          command: |
            cd docker/compose/monolithic && WHYIS_IMAGE_TAG=latest docker-compose build whyis
      - run:
          name: Run tests
          command: |
            bash .circleci/test-ci.sh tetherlessworld/whyis:latest
      - store_test_results:
          path: test-results
      - run:
          name: Build split Docker image
          command: |
            cd docker/compose/split/app && WHYIS_IMAGE_TAG=latest docker-compose build whyis-server
      - run:
          name: Build and push Docker images
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              # Monolithic latest, push (build above)
              docker login -u $DOCKER_USER -p $DOCKER_PASS && cd docker/compose/monolithic && WHYIS_IMAGE_TAG=latest docker-compose push whyis
              # Monolithic master, build and push
              docker login -u $DOCKER_USER -p $DOCKER_PASS && cd docker/compose/monolithic && WHYIS_IMAGE_TAG=master docker-compose build whyis && WHYIS_IMAGE_TAG=master docker-compose push whyis
              # docker login -u $DOCKER_USER -p $DOCKER_PASS && cd docker/compose/split/app && docker-compose push whyis-server
            fi
