# whyis testing
# Adapted from https://circleci.com/blog/how-to-build-a-docker-image-on-circleci-2-0/
version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:18.06.0-ce
        environment:
          BUILD_MODE: master
    steps:
      - run:
          name: Install system dependencies with apk
          command: apk update && apk add bash git
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            apk add python-dev libffi-dev openssl-dev gcc libc-dev make
            pip install docker-compose
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            ls ~ && cd docker/compose/dev && docker-compose build whyis
      - run:
          name: Run tests
          command: |
            bash .circleci/test-ci.sh
      - store_test_results:
          path: test-results
      - run:
          name: Push Docker image
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS && cd docker/compose/dev && docker-compose push whyis
