# whyis testing
# Adapted from https://circleci.com/blog/how-to-build-a-docker-image-on-circleci-2-0/
version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
        environment:
          BUILD_MODE: master
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            docker build -t whyis -f dockerfiles/Dockerfile .
      - run:
          name: Run tests
          command: |
            sh .circleci/test-ci.sh
      - store_test_results:
          path: test-results
  