openapi: 3.0.2
info: 
  title: Whyis
  description: [to be added]
  version: 0.1.0
  # TOS, contact, license all optional
paths:
  /?view=labels:
    get:
      description: Returns a label for each specified URI. The label returned will be taken from, in order of priority: skos:prefLabel, rdfs:label, schema:name, dc:title, foaf:name, or schema:name.
      parameters:
      - name: uris
        in: query
        description: A comma-delimited list of URIs.
        required: true
      responses:
        '200':
         content:
            application/json:
              schema:
                type: object
                #it's a dict of uri : label but i have no idea how to represent this according to openapi

  /?view=latest:
    get:
      description: Lists recently-changed entities. # TODO How recently-changed?
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required:
                   - about
                   - updated
                  properties:
                    about:
                      type: string
                      format: url
                    updated:
                      type: string
                      format: timestamp # yyyy-mm-ddThh:mm:ss.118000+00:00

  /?view=resolve:
    get:
      description: Allows searching for entities by a number of properties representing plaintext identifiers. This includes dc:title, rdfs:label, skos:prefLabel, skos:altLabel, foaf:name, and dc:identifier. Entities of type sio:Term are excluded.
      parameters:
      - name: term
        in: query
        description: The string to search for
        required: true
        schema:
          type: string
      - name: type
        in: query
        description: A url corresponding to an rdf:type. If present, only entities of the specified type will be returned.
        required: false
        schema:
          type: string
          format: url
      - name: context
        in: query
        description: The string to search for
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    node:
                      type: uri
                    label:
                      type: string
                    preflabel:
                      type: string
                    score:
                      type: float