openapi: 3.0.2
info: 
  title: Whyis
  description: [to be added]
  version: 0.1.0
  # TOS, contact, license all optional
paths:
  /?view=labels:
    get:
      description: Crashes with the following error message: "jinja2.exceptions.UndefinedError: 'werkzeug.datastructures.ImmutableMultiDict object' has no attribute 'uris'"
      #responses:
      #  '500':
      #    content:
      #      application/json:
      #        schema:
      #          type: object

  /?view=latest:
    get:
      description: Lists recently-changed entities. # TODO How recently-changed?
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required:
                   - about
                   - updated
                  properties:
                    about:
                      type: string
                      format: url
                    updated:
                      type: string
                      format: timestamp # yyyy-mm-ddThh:mm:ss.118000+00:00

  /?view=resolve:
    get:
      description: Allows searching for terms by a number of properties representing plaintext identifiers (such as rdfs:label, dc:title, and foaf:name).
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    node:
                      type: uri
                    label:
                      type: string
                    preflabel:
                      type: string
                    score:
                      type: float